spring:
  datasource:
    name: nyps
    url: jdbc:mysql://121.199.5.203:3306/nyps?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 114019
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:templates/,classpath:static/
  thymeleaf:
    suffix: .html
  mvc:
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: competition_2020.pojo
