spring:
  datasource:
    name: nyps
    url: jdbc:mysql://121.199.5.203/nyps?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 114019
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/templates,classpath:/static,classpath:/resources,classpath:/META-INF/resources
  thymeleaf:
    suffix: .html
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: competition_2020.pojo
server:
  port: 8080